[manager]
prepend_keymap = [
  { on = [ "E" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
  { on = [ "-" ], run = "plugin eza-preview --args='--inc-level'", desc = "Increment tree level" },
  { on = [ "_" ], run = "plugin eza-preview --args='--dec-level'", desc = "Decrement tree level" },
  { on = [ "$" ], run = "plugin eza-preview --args='--toggle-follow-symlinks'", desc = "Toggle tree follow symlinks" },
  { on = ["<C-e>"], run = "seek 5" },
  { on = ["<C-y>"], run = "seek -5" },
  { on = ["1"], run = "plugin fast-enter", desc = "Enter the subfolder faster, or open file directly"},
]


[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
