# : Manager [[[

[mgr]
cwd = { fg = "#e5e3d6" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#6fd5b2", bg = "#6fd5b2" }
marker_cut      = { fg = "#beecdc", bg = "#beecdc" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a3d0c0", bg = "#a3d0c0" }

# Count
count_copied   = { fg = "#002019", bg = "#beecdc" }
count_cut      = { fg = "#002019", bg = "#beecdc" }
count_selected = { fg = "#2f3300", bg = "#a3d0c0" }

# Border
border_symbol = "│"
border_style  = { fg = "#c6cc7a" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c6cc7a", bold = true, bg = "#13140c" }
inactive  = { fg = "#c8c9a6", bg = "#13140c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c6cc7a", fg = "#2f3300", bold = true }
normal_alt  = { bg = "#47483b", fg = "#c8c7b7" }

# Select mode
select_main = { bg = "#c8c9a6", fg = "#303219", bold = true }
select_alt  = { bg = "#47483b", fg = "#c8c7b7" }

# Unset mode
unset_main = { bg = "#a3d0c0", fg = "#07372c", bold = true }
unset_alt  = { bg = "#47483b", fg = "#c8c7b7" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#848551" }
perm_write = { fg = "#4a9077" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#48c99c" }
perm_sep   = { fg = "#b0bd26" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c6cc7a", bg = "#3a3a31" }
progress_error  = { fg = "#ffb4ab", bg = "#3a3a31" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a3a31" }
cand = { fg = "#c6cc7a" }
rest = { fg = "#2f3300" }
desc = { fg = "#e5e3d6" }
separator = " ▶ "
separator_style = { fg = "#e5e3d6" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#a3d0c0" }
title_warn  = { fg = "#c6cc7a" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#c6cc7a" }
active = { fg = "#a3d0c0", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c6cc7a" }
value  = { fg = "#e5e3d6" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#c6cc7a", bg = "#2f3300" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c6cc7a" }
title   = {}
hovered = { fg = "#beecdc", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e5e3d6" }
run    = { fg = "#e5e3d6" }
footer = { fg = "#303219", bg = "#c8c9a6" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e5e3d6" },
    { url = "*/", fg = "#c6cc7a" },
]

# : ]]]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#c6cc7a" },
	{ if = "link", text = "", fg = "#c6cc7a" },
	{ if = "block", text = "", fg = "#c6cc7a" },
	{ if = "char", text = "", fg = "#c6cc7a" },
	{ if = "fifo", text = "", fg = "#c6cc7a" },
	{ if = "sock", text = "", fg = "#c6cc7a" },
	{ if = "sticky", text = "", fg = "#c6cc7a" },
	{ if = "dummy", text = "", fg = "#c6cc7a" },

	# Fallback
	{ if = "dir", text = "", fg = "#c6cc7a" },
	{ if = "exec", text = "", fg = "#c6cc7a" },
	{ if = "!dir", text = "", fg = "#c6cc7a" },
]
# : }}}
