cursor            #a1c9fd
cursor_text_color #0b0e13

foreground            #e1e2e8
background            #0b0e13
selection_foreground  #2e3135
selection_background  #1d2024
url_color             #533f5f

#: black
color0  #0b0e13
color8  #43474e
#: red
color1  #ffb4ab
color9  #ffb4ab
#: green
color2  #a1c9fd
color10 #a1c9fd
#: yellow
color3  #bbc7db
color11 #bbc7db
#: blue
color4  #a1c9fd
color12 #a1c9fd
#: magenta
color5  #3c4858
color13 #3c4858
#: cyan
color6  #533f5f
color14 #533f5f
#: white
color7  #e1e2e8
color15 #36393e

mark1_foreground #0b0e13
mark1_background #a1c9fd
mark2_foreground #0b0e13
mark2_background #3c4858
mark3_foreground #0b0e13
mark3_background #d7bde4

active_tab_foreground #0b0e13
active_tab_background #a1c9fd
inactive_tab_foreground #c3c6cf
inactive_tab_background #191c20

active_border_color #a1c9fd
inactive_border_color #191c20