cursor            #d8c76f
cursor_text_color #100e07

foreground            #e8e2d4
background            #100e07
selection_foreground  #333027
selection_background  #222017
url_color             #2a4e39

#: black
color0  #100e07
color8  #4a4739
#: red
color1  #ffb4ab
color9  #ffb4ab
#: green
color2  #d8c76f
color10 #d8c76f
#: yellow
color3  #d0c7a2
color11 #d0c7a2
#: blue
color4  #d8c76f
color12 #d8c76f
#: magenta
color5  #4d472b
color13 #4d472b
#: cyan
color6  #2a4e39
color14 #2a4e39
#: white
color7  #e8e2d4
color15 #3c3930

mark1_foreground #100e07
mark1_background #d8c76f
mark2_foreground #100e07
mark2_background #4d472b
mark3_foreground #100e07
mark3_background #a8d0b5

active_tab_foreground #100e07
active_tab_background #d8c76f
inactive_tab_foreground #ccc6b5
inactive_tab_background #1e1c13

active_border_color #d8c76f
inactive_border_color #1e1c13