cursor            #80d4d8
cursor_text_color #090f10

foreground            #dde4e3
background            #090f10
selection_foreground  #2b3232
selection_background  #1a2121
url_color             #364764

#: black
color0  #090f10
color8  #3f4949
#: red
color1  #ffb4ab
color9  #ffb4ab
#: green
color2  #80d4d8
color10 #80d4d8
#: yellow
color3  #b1cccd
color11 #b1cccd
#: blue
color4  #80d4d8
color12 #80d4d8
#: magenta
color5  #324b4c
color13 #324b4c
#: cyan
color6  #364764
color14 #364764
#: white
color7  #dde4e3
color15 #343a3b

mark1_foreground #090f10
mark1_background #80d4d8
mark2_foreground #090f10
mark2_background #324b4c
mark3_foreground #090f10
mark3_background #b5c7e9

active_tab_foreground #090f10
active_tab_background #80d4d8
inactive_tab_foreground #bec8c9
inactive_tab_background #161d1d

active_border_color #80d4d8
inactive_border_color #161d1d