--ozone-platform=wayland
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,AcceleratedVideoEncoder,WaylandWindowDecorations,WebContentsForceDark
--use-gl=desktop
--ignore-gpu-blocklist
--password-store=basic