# Matugen Hyprlock Colors — Base16 (Material You → base00–base0f)

$base00 = rgba(101213ff)
$base01 = rgba(59636eff)
$base02 = rgba(59636eff)
$base03 = rgba(59636eff)
$base04 = rgba(a19a3bff)
$base05 = rgba(c3c3c4ff)
$base06 = rgba(c3c3c4ff)
$base07 = rgba(c3c3c4ff)

$base08 = rgba(719055ff)
$base09 = rgba(719055ff)
$base0A = rgba(a19a3bff)
$base0B = rgba(689467ff)
$base0C = rgba(dac99fff)
$base0D = rgba(689467ff)
$base0E = rgba(beb290ff)
$base0F = rgba(458487ff)

$background = $base00
$on_background = $base05
$primary = $base0D
$on_primary = $base00
$primary_container = $base0C
$on_primary_container = $base05
$secondary = $base0E
$on_secondary = $base00
$surface = $base00
$on_surface = $base05
$surface_variant = $base01
$on_surface_variant = $base04
$surface_container = $base02
$surface_container_high = $base01
$surface_container_highest = $base03
$outline = $base04
$outline_variant = $base03
$muted = $base03
$error = $base08
$on_error = $base00
$source_color = $base0F
$icolor = $base0F
$tertiary = $base09
$on_tertiary = $base00
$tertiary_container = $base0A

$bg = $base00
$fg = $base05
$text = $base05
$accent = $base0D
$accent2 = $base0E
$bg0 = $base00
$bg1 = $base02
$bg2 = $base01
$grey0 = $base03
$red = $base08
$green = $base0B
$yellow = $base0A
$blue = $base0D
$surface_dim = $base00
$surface_bright = $base07
$inactive_border = $base01

$lock_input_bg = rgba(2e2921cc)
$lock_accent = $base0D