cursor            #af92af
cursor_text_color #1b1e25

foreground            #c6c6c8
background            #1b1e25
selection_foreground  #1b1e25
selection_background  #af92af
url_color             #d7dee9

#: black
color0  #1b1e25
color8  #626878
#: red
color1  #7fa0c0
color9  #7fa0c0
#: green
color2  #af92af
color10 #af92af
#: yellow
color3  #82a3c2
color11 #82a3c2
#: blue
color4  #af92af
color12 #af92af
#: magenta
color5  #93c3d2
color13 #93c3d2
#: cyan
color6  #d7dee9
color14 #d7dee9
#: white
color7  #c6c6c8
color15 #c6c6c8

mark1_foreground #1b1e25
mark1_background #af92af
mark2_foreground #1b1e25
mark2_background #93c3d2
mark3_foreground #1b1e25
mark3_background #7fa0c0

active_tab_foreground #1b1e25
active_tab_background #af92af
inactive_tab_foreground #82a3c2
inactive_tab_background #626878

active_border_color #af92af
inactive_border_color #626878