cursor            #a5b0a0
cursor_text_color #121212

foreground            #e6e6e6
background            #121212
selection_foreground  #121212
selection_background  #a5b0a0
url_color             #9cb0ad

#: black
color0  #121212
color8  #b9bdc2
#: red
color1  #b0a0a5
color9  #b0a0a5
#: green
color2  #a5b0a0
color10 #a5b0a0
#: yellow
color3  #b0ada0
color11 #b0ada0
#: blue
color4  #a5b0a0
color12 #a5b0a0
#: magenta
color5  #9ca8b0
color13 #9ca8b0
#: cyan
color6  #9cb0ad
color14 #9cb0ad
#: white
color7  #e6e6e6
color15 #444444

mark1_foreground #121212
mark1_background #a5b0a0
mark2_foreground #121212
mark2_background #9ca8b0
mark3_foreground #121212
mark3_background #a89cb0

active_tab_foreground #121212
active_tab_background #a5b0a0
inactive_tab_foreground #888c94
inactive_tab_background #1e1e1e

active_border_color #a5b0a0
inactive_border_color #1e1e1e