cursor            #84d2e5
cursor_text_color #14181b

foreground            #d3c6aa
background            #14181b
selection_foreground  #14181b
selection_background  #84d2e5
url_color             #3e4565

#: black
color0  #14181b
color8  #657366
#: red
color1  #e67e80
color9  #e67e80
#: green
color2  #84d2e5
color10 #84d2e5
#: yellow
color3  #b2cbd2
color11 #b2cbd2
#: blue
color4  #84d2e5
color12 #84d2e5
#: magenta
color5  #334a50
color13 #334a50
#: cyan
color6  #3e4565
color14 #3e4565
#: white
color7  #d3c6aa
color15 #3c4851

mark1_foreground #14181b
mark1_background #84d2e5
mark2_foreground #14181b
mark2_background #334a50
mark3_foreground #14181b
mark3_background #d699b6

active_tab_foreground #14181b
active_tab_background #84d2e5
inactive_tab_foreground #859289
inactive_tab_background #1e2429

active_border_color #84d2e5
inactive_border_color #1e2429