# dunstify
# Autogenerated from man page /usr/share/man/man1/dunstify.1.gz
complete -c dunstify -s '?' -l help -d 'X Item "-?, --help" Show help options'
complete -c dunstify -s a -l appname -d 'X Item "-a, --appname=NAME" Set the app name of the notification'
complete -c dunstify -s u -l urgency -d 'X Item "-u, --urgency=URG" Set the urgency level (low, normal, critical) of t…'
complete -c dunstify -s h -l hints -d 'X Item "-h, --hints=HINT" Specifies hints to pass'
complete -c dunstify -s A -l action -d 'X Item "-A, --action=ACTION" Specifies the actions to display to the user'
complete -c dunstify -s t -l timeout -d 'X Item "-t, --timeout=TIMEOUT" The time in milliseconds until the notificatio…'
complete -c dunstify -s i -l icon -d 'X Item "-i, --icon=ICON" Specifies an icon to display with the notification'
complete -c dunstify -s I -l raw_icon -d 'X Item "-I, --raw_icon=PATH" Path to the icon to be sent as raw image data'
complete -c dunstify -s c -l capabilities -d 'X Item "-c, --capabilities" Print the server capabilities and exit'
complete -c dunstify -s s -l serverinfo -d 'X Item "-s, --serverinfo" Print server information and exit'
complete -c dunstify -s p -l printid -d 'X Item "-p, --printid" Print id, which can be used to update/replace this not…'
complete -c dunstify -s r -l replace -d 'X Item "-r, --replace=ID" Set the id of this notification to The ID of the no…'
complete -c dunstify -s C -l close -d 'X Item "-C, --close=ID" Close the notification with the specified ID'
complete -c dunstify -s b -l block

