# grimblast
# Autogenerated from man page /usr/share/man/man1/grimblast.1.gz
complete -c grimblast -l openfile -d 'Uses dbus to display the folder containing the file when interacting with the'
complete -c grimblast -l cursor -d 'Include cursors in the screenshot'
complete -c grimblast -l freeze -d 'Freezes the screen before area selection'
complete -c grimblast -l wait -d 'Wait for N seconds before taking a screenshot.  Decimal values'
complete -c grimblast -l scale -d 'Passes the `-s` argument to `grim`'

