# powerpill.json
# Autogenerated from man page /usr/share/man/man1/powerpill.json.1.gz
complete -c 'powerpill.json' -l conf-path
complete -c 'powerpill.json' -l no-motd -d 'Sometimes Rsync will attempt to redownload a file if the modification time of…'
complete -c 'powerpill.json' -l verbose -d 'AUTHORS Xyne'

