# systemd-keyutil
# Autogenerated from man page /usr/share/man/man1/systemd-keyutil.1.gz
complete -c systemd-keyutil -l private-key -l private-key-source -l certificate -l certificate-source -d 'Set the private key and certificate to use'
complete -c systemd-keyutil -s h -l help -d 'Print a short help text and exit'
complete -c systemd-keyutil -l version -d 'Print a short version string and exit'

