# systemd-sbsign
# Autogenerated from man page /usr/share/man/man1/systemd-sbsign.1.gz
complete -c systemd-sbsign -l output -d 'Specifies the path where to write the signed PE binary'
complete -c systemd-sbsign -l private-key -l private-key-source -l certificate -l certificate-source -d 'Set the Secure Boot private key and certificate for use with the sign'
complete -c systemd-sbsign -s h -l help -d 'Print a short help text and exit'
complete -c systemd-sbsign -l version -d 'Print a short version string and exit'

