# unflatten
# Autogenerated from man page /usr/share/man/man1/unflatten.1.gz
complete -c unflatten -s l -d 'The minlen of leaf edges is staggered between 1 and len (a small integer)'
complete -c unflatten -s f -d 'Applies the -l option to fanout nodes whose indegree and outdegree are both 1'
complete -c unflatten -s c -d 'Form disconnected nodes into chains of up to len edges'
complete -c unflatten -s o -d 'causes the output to be written to the specified file; by default, output is …'
complete -c unflatten -s '?' -d 'Prints the usage and exits.  OPERANDS The following operand is supported:'

