# uwsm
# Autogenerated from man page /usr/share/man/man1/uwsm.1.gz
complete -c uwsm -s r -d 'T}	T{ Also remove units (all or only compositor-specific).  T} T{'
complete -c uwsm -s n -d 'T}	T{ Dry run, do not stop or remove anything.  T} app'
complete -c uwsm -s s -d 'T}	T{ Slice selector (default: a): T} T{'
complete -c uwsm -s t -d 'T}	T{ Type of unit to launch (default: scope, can be preset by UWSM_APP_UNIT_…'
complete -c uwsm -s a -d 'T}	T{ Override app name (a substring in unit name).  T} T{'
complete -c uwsm -s u -d 'T}	T{ Override the whole autogenerated unit name.  T} T{'
complete -c uwsm -s d -d 'T}	T{ Unit Description.  T} T{'
complete -c uwsm -s S -d 'T}	T{ Silence stdout, stderr, or both.  T} T{'
complete -c uwsm -s T -d 'T}	T{ Launch app in a terminal'

