# vapigen-0.56
# Autogenerated from man page /usr/share/man/man1/vapigen-0.56.1.gz
complete -c 'vapigen-0.56' -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c 'vapigen-0.56' -l vapidir -d 'Look for package bindings in DIRECTORY'
complete -c 'vapigen-0.56' -l girdir -d 'Look for GIR bindings in DIRECTORY'
complete -c 'vapigen-0.56' -l metadatadir -d 'Look for GIR . metadata files in DIRECTORY'
complete -c 'vapigen-0.56' -l nostdpkg -d 'Do not include standard packages'
complete -c 'vapigen-0.56' -l pkg -d 'Include binding for PACKAGE'
complete -c 'vapigen-0.56' -l library -d 'Library name'
complete -c 'vapigen-0.56' -s d -l directory -d 'Output directory'
complete -c 'vapigen-0.56' -l disable-warnings -d 'Disable warnings'
complete -c 'vapigen-0.56' -l version -d 'Display version number'
complete -c 'vapigen-0.56' -s q -l quiet -d 'Do not print messages to the console'

