# xkbcli-dump-keymap-wayland
# Autogenerated from man page /usr/share/man/man1/xkbcli-dump-keymap-wayland.1.gz
complete -c xkbcli-dump-keymap-wayland -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-dump-keymap-wayland -o '\\-raw' -d 'Print the raw keymap, without parsing it'

