Net/ThemeName "Graphite-Dark-compact"
Net/IconThemeName "GreyStone"
Gtk/CursorThemeName "Bibata-Modern-Classic-Gruvbox"
Gtk/CursorThemeSize 24
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
