#!/usr/bin/env bash
# Rebuild ~/.config/waypaper/style.css as ONE file (no @import).
# GTK load_from_data() cannot resolve @import; classic waypaper uses that path
# when not launched through the patched wrapper.
set -euo pipefail

FONTS_SH="${FONTS_SH:-$HOME/.config/settings/fonts.sh}"
[[ -f "$FONTS_SH" ]] && source "$FONTS_SH"

OUT="$HOME/.config/waypaper/style.css"
COLORS="$HOME/.config/waypaper/colors/matugen.css"
mkdir -p "$(dirname "$OUT")"

{
    cat <<EOF
/* Generated by waypaper-rebuild-style.sh — do not edit directly */
/* Fonts: ~/.config/settings/fonts.sh | Colors: waypaper/colors/matugen.css */

/* UI chrome → FONT_UI */
window,
button,
togglebutton,
label,
combobox,
menu,
menuitem,
checkmenuitem {
    font-family: "${FONT_UI:-Agave Nerd Font Propo}", sans-serif;
    font-size: ${FONT_SIZE_WAYPAPER_UI:-11}pt;
}

/* Search / paths / numeric fields → FONT_TEXT */
entry {
    font-family: "${FONT_TEXT:-ShureTechMono Nerd Font}", monospace;
    font-size: ${FONT_SIZE_WAYPAPER_TEXT:-11}pt;
}

/* Wallpaper file names (thumbnail tooltips) → FONT_TEXT */
tooltip {
    font-family: "${FONT_TEXT:-ShureTechMono Nerd Font}", monospace;
    font-size: ${FONT_SIZE_WAYPAPER_TOOLTIP:-10}pt;
}

EOF

    if [[ -f "$COLORS" ]]; then
        echo ""
        echo "/* --- matugen colors --- */"
        # Strip any old @import / generator banner from colors file
        grep -v '^@import' "$COLORS" | grep -v '^/\* Generated by apply-fonts' || true
    fi

    RICING="$HOME/.config/waypaper/ricing.css"
    if [[ -f "$RICING" ]]; then
        echo ""
        echo "/* --- ricing overrides (edit ~/.config/waypaper/ricing.css) --- */"
        cat "$RICING"
    fi

} > "$OUT"

echo "  ✓ Rebuilt waypaper/style.css (monolithic, no @import)"