#!/usr/bin/env bash
# matugen-posthook-grok.sh — keep ~/.grok/themes/matugen.toml in sync with matugen
#
# Grok Build 0.2.56 only ships built-in themes. This hook regenerates the custom
# theme file on every wallpaper change so it is ready when the CLI loads user themes.
# Until then, restart Grok and try: /theme matugen

set -euo pipefail

GROK_THEME="${HOME}/.grok/themes/matugen.toml"
JSON_CACHE="${HOME}/.cache/matugen/current.json"

mkdir -p "${HOME}/.grok/themes"

if [[ -f "$JSON_CACHE" ]]; then
    python3 - "$JSON_CACHE" >"$GROK_THEME" <<'PYEOF'
import sys, json

def normalize_colors(data):
    raw = data.get("colors", {})
    if isinstance(raw.get("default"), dict) and any(
        isinstance(v, dict) and "hex" in v for v in raw["default"].values()
    ):
        return raw["default"]
    out = {}
    for name, val in raw.items():
        if not isinstance(val, dict):
            continue
        if "hex" in val:
            out[name] = val
        elif isinstance(val.get("default"), dict):
            color = val["default"].get("color") or val["default"].get("hex")
            if color:
                out[name] = {"hex": color}
    return out

def getc(colors, name, fallback="#888888"):
    c = colors.get(name, {})
    return c.get("hex", fallback) if isinstance(c, dict) else fallback

data = json.loads(open(sys.argv[1], encoding="utf-8").read())
colors = normalize_colors(data)

slots = {
    "bg_base": "surface_container_lowest",
    "bg_light": "surface_container_low",
    "bg_dark": "surface_container",
    "bg_highlight": "surface_container_high",
    "bg_hover": "surface_container_highest",
    "bg_terminal": "surface_container_lowest",
    "bg_visual": "surface_container_low",
    "accent_user": "primary",
    "accent_assistant": "secondary",
    "accent_thinking": "tertiary",
    "accent_tool": "tertiary_container",
    "accent_system": "outline",
    "accent_error": "error",
    "accent_success": "primary",
    "accent_running": "tertiary",
    "accent_skill": "secondary_container",
    "accent_interjection": "primary",
    "accent_plan": "secondary",
    "accent_verify": "primary",
    "accent_best_of_n": "tertiary",
    "accent_feedback": "secondary_container",
    "accent_remember": "tertiary_container",
    "accent_model": "primary_fixed",
    "text_primary": "on_surface",
    "text_secondary": "on_surface_variant",
    "gray_dim": "outline_variant",
    "gray": "outline",
    "gray_bright": "on_surface_variant",
    "command": "primary",
    "path": "secondary",
    "running": "tertiary",
    "warning": "tertiary_container",
    "fuzzy_accent": "primary",
    "selection_border": "primary",
    "hover_border": "secondary",
    "prompt_border": "outline_variant",
    "prompt_border_active": "primary",
    "scrollbar_bg": "surface_container_low",
    "scrollbar_fg": "outline_variant",
    "paste_bg": "surface_container_high",
    "paste_fg": "on_surface",
    "paste_dim": "on_surface_variant",
    "diff_delete_bg": "error_container",
    "diff_delete_fg": "on_error_container",
    "diff_insert_bg": "primary_container",
    "diff_insert_fg": "on_primary_container",
    "diff_equal_fg": "on_surface_variant",
    "diff_gutter_fg": "outline_variant",
    "md_heading_h1": "primary",
    "md_heading_h2": "secondary",
    "md_heading_h3": "tertiary",
    "md_heading_h4": "on_surface",
    "md_heading_h5": "on_surface_variant",
    "md_heading_h6": "outline",
    "md_code": "tertiary_container",
    "md_code_bg": "surface_container_high",
    "md_text": "on_surface",
    "md_muted": "on_surface_variant",
    "md_task_checked": "primary",
    "md_task_unchecked": "outline_variant",
    "link_fg": "primary",
}

print("# Auto-generated by matugen — do not edit manually.")
print("# Source: ~/.config/matugen/templates/grok-theme.toml")
print()
print("[colors]")
for slot, material in slots.items():
    print(f'{slot} = "{getc(colors, material)}"')
PYEOF
fi

[[ -s "$GROK_THEME" ]] || exit 0

touch "$GROK_THEME" 2>/dev/null || true