#!/usr/bin/env bash
# Static Gruvbox dark palette for the install path only (no matugen / colors.sh).

export COLOR_BACKGROUND="#282828"
export COLOR_SURFACE="#282828"
export COLOR_SURFACE_CONTAINER="#3c3836"
export COLOR_SURFACE_CONTAINER_HIGH="#504945"
export COLOR_ON_SURFACE="#ebdbb2"
export COLOR_ON_SURFACE_VARIANT="#a89984"
export COLOR_ON_BACKGROUND="#ebdbb2"
export COLOR_PRIMARY="#fe8019"
export COLOR_ON_PRIMARY="#282828"
export COLOR_SECONDARY="#83a598"
export COLOR_ON_SECONDARY="#282828"
export COLOR_TERTIARY="#b8bb26"
export COLOR_OUTLINE="#504945"
export COLOR_ERROR="#fb4934"
export COLOR_ON_ERROR="#282828"
export COLOR_SUCCESS="#b8bb26"
export COLOR_TEXT="#ebdbb2"
export COLOR_ACCENT="${COLOR_PRIMARY}"
export COLOR_BG="${COLOR_SURFACE}"
export COLOR_FG="${COLOR_ON_SURFACE}"