-- Matugen integration for Neovim
-- Uses mini.base16 + the file generated by matugen/templates/neovim-mini.lua
--
-- Live reload: matugen sends SIGUSR1 after writing the new theme file.
-- The Signal autocmd below will pick it up in all running Neovim instances.

return {
  {
    "nvim-mini/mini.base16",
    lazy = false,
    priority = 1000, -- load very early so colors are set before UI plugins
    config = function()
      local function refresh_ui()
        -- mini.base16 sets highlights directly (no ColorScheme event), but lualine's
        -- "auto" theme snapshots colors at setup — re-run it after palette changes.
        vim.schedule(function()
          if package.loaded["lualine"] then
            pcall(require("lualine").setup)
          end
          pcall(vim.cmd.doautocmd, "ColorScheme")
          pcall(vim.cmd.redrawstatus)
          pcall(vim.cmd.redrawtabline)
        end)
      end

      local function load_matugen()
        local path = vim.fn.stdpath("config") .. "/lua/matugen-theme.lua"
        if vim.fn.filereadable(path) == 1 then
          dofile(path)
        else
          -- First run / no wallpaper yet → gentle fallback
          -- You can change this to any colorscheme you have installed.
          pcall(vim.cmd.colorscheme, "tokyonight-night")
        end
        refresh_ui()
      end

      load_matugen()

      -- Live reload when matugen runs (pkill -SIGUSR1 nvim from the template hook)
      vim.api.nvim_create_autocmd("Signal", {
        pattern = "SIGUSR1",
        callback = function()
          load_matugen()
        end,
      })
    end,
  },
}
