-- Matugen integration for Neovim
-- Uses mini.base16 + the file generated by matugen/templates/neovim-mini.lua
--
-- Live reload: matugen sends SIGUSR1 after writing the new theme file.
-- The Signal autocmd below will pick it up in all running Neovim instances.

return {
  {
    "nvim-mini/mini.base16",
    lazy = false,
    priority = 1000, -- load very early so colors are set before UI plugins
    config = function()
      local function refresh_ui()
        -- Re-apply lualine without wiping LazyVim's config. Official colorschemes
        -- fire ColorScheme; mini.base16 does not, so we always refresh the bar.
        vim.schedule(function()
          if package.loaded["lualine"] then
            local ll = require("lualine")
            local ok, cfg = pcall(ll.get_config)
            if ok and cfg then
              pcall(ll.setup, cfg)
            else
              pcall(ll.setup)
            end
          end
          pcall(vim.cmd.doautocmd, "ColorScheme")
          pcall(vim.cmd.redrawstatus)
          pcall(vim.cmd.redrawtabline)
        end)
      end

      local function load_matugen()
        local path = vim.fn.stdpath("config") .. "/lua/matugen-theme.lua"
        if vim.fn.filereadable(path) == 1 then
          -- Super+W writes either an official :colorscheme or mini.base16 here.
          dofile(path)
        else
          pcall(vim.cmd.colorscheme, "gruvbox")
        end
        refresh_ui()
      end

      load_matugen()

      -- Live reload when matugen runs (pkill -SIGUSR1 nvim from the template hook)
      vim.api.nvim_create_autocmd("Signal", {
        pattern = "SIGUSR1",
        callback = function()
          load_matugen()
        end,
      })
    end,
  },
}
