# -----------------------------------------------------
# Autostart
# ----------------------------------------------------- 

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-kde-agent

# Using hypridle to start hyprlock
exec-once = hypridle & waybar

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Start nwg-dock-hyprland
exec-once = nwg-dock-hyprland

# Symlinks for scripts
exec-once = waypaper-engine daemon
exec-once = killall waybar && hyprpaper && waypaper --restore

# Load Dunst Notification Manager
exec-once = dunst

# Load GTK settings
exec-once = ~/scripts/gtk.sh

# hyprctl.sh
exec = ~/.config/hypr/hpyrctl/hyprctl.sh

# Dolphin Fix.sh
exec-once = ~/scripts/dolphin_fix.sh

# SSH-Add for Git
exec-once = ~/scripts/ssh_add.sh

# Hyprpm Update

exec-once = ~/scripts/hyprpm.sh
