#!/usr/bin/env bash
# audio-setup.sh — detect PipeWire sinks, play a test tone, persist the default
#
#   bash ~/.hyprgruv/lib/scripts/audio-setup.sh          # interactive (install / 04-config)
#   bash ~/.hyprgruv/lib/scripts/audio-setup.sh --apply  # re-apply saved sink (login)
set -euo pipefail
IFS=$'\n\t'

HYPR_DIR="${HYPRGRUV_DIR:-$HOME/.hyprgruv}"
# shellcheck source=/dev/null
[[ -f "$HYPR_DIR/lib/common.sh" ]] && source "$HYPR_DIR/lib/common.sh"

SETTINGS_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/settings"
SINK_FILE="$SETTINGS_DIR/audio_sink.sh"
WP_DROPIN="${XDG_CONFIG_HOME:-$HOME/.config}/wireplumber/wireplumber.conf.d/51-hyprgruv-default-sink.conf"
TEST_SOUNDS=(
    /usr/share/sounds/freedesktop/stereo/audio-test-signal.oga
    /usr/share/sounds/freedesktop/stereo/complete.oga
    /usr/share/sounds/freedesktop/stereo/bell.oga
)

if ! declare -F log_status >/dev/null 2>&1; then
    log_status() { echo "  $*"; }
    log_success() { echo "  ✓ $*"; }
    log_warning() { echo "  ! $*" >&2; }
    log_error() { echo "  ✗ $*" >&2; }
    display_header() { echo "== $* =="; }
fi

pipewire_ready() {
    command -v pactl >/dev/null 2>&1 || return 1
    pactl info >/dev/null 2>&1
}

short_label() {
    local desc="$1"
    desc="${desc#*HD Audio) }"
    desc="${desc#*(HD Audio) }"
    printf '%s' "$desc"
}

# Prints: name<TAB>label  (label includes * for the current default)
list_sink_rows() {
    python3 - <<'PY'
import json, subprocess, sys

def run(cmd):
    return subprocess.check_output(cmd, text=True, stderr=subprocess.DEVNULL)

try:
    sinks = json.loads(run(["pactl", "--format=json", "list", "sinks"]))
except Exception:
    sys.exit(1)

default = ""
try:
    for line in run(["pactl", "get-default-sink"]).splitlines():
        default = line.strip()
except Exception:
    pass

wp_ids = {}
try:
    for line in run(["wpctl", "list", "audio", "sinks"]).splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            wp_ids[parts[1]] = parts[0]
except Exception:
    pass

for s in sinks:
    name = s.get("name") or ""
    desc = s.get("description") or name
    for prefix in ("500 Series Chipset Family On-Package High Definition Audio (HD Audio) ",
                   "(HD Audio) "):
        if desc.startswith(prefix):
            desc = desc[len(prefix):]
    mark = " *" if name == default else ""
    wp = wp_ids.get(name, "")
    print(f"{name}\t{desc}{mark}\t{wp}")
PY
}

play_test() {
    local name="$1"
    local f
    pactl set-sink-mute "$name" 0 >/dev/null 2>&1 || true
    pactl set-sink-volume "$name" 75% >/dev/null 2>&1 || true
    for f in "${TEST_SOUNDS[@]}"; do
        [[ -f "$f" ]] || continue
        paplay --device="$name" "$f" >/dev/null 2>&1 && return 0
    done
    if command -v speaker-test >/dev/null 2>&1; then
        PULSE_SINK="$name" timeout 2 speaker-test -D pulse -c 2 -t sine -f 880 -l 1 >/dev/null 2>&1 || true
        return 0
    fi
    return 1
}

set_default_now() {
    local name="$1"
    local wp_id="${2:-}"
    pactl set-default-sink "$name"
    if [[ -z "$wp_id" ]]; then
        wp_id="$(wpctl list audio sinks 2>/dev/null | awk -v n="$name" '$2==n {print $1; exit}')"
    fi
    if [[ -n "$wp_id" ]]; then
        wpctl set-default "$wp_id" >/dev/null 2>&1 || true
    fi
}

persist_choice() {
    local name="$1"
    mkdir -p "$SETTINGS_DIR" "$(dirname "$WP_DROPIN")"
    printf '%s\n' "$name" >"$SINK_FILE"
    cat >"$WP_DROPIN" <<EOF
# Generated by hyprgruv audio-setup.sh — machine-local (do not commit)
# Raises session priority so this sink wins over HDMI/DP when both are present.
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "${name}" }
    ]
    actions = {
      update-props = {
        priority.session = 2100
        priority.driver = 2100
      }
    }
  }
]
EOF
}

apply_saved() {
    pipewire_ready || return 0
    [[ -f "$SINK_FILE" ]] || return 0
    local name
    name="$(tr -d '[:space:]' <"$SINK_FILE")"
    [[ -n "$name" ]] || return 0
    if ! pactl list short sinks 2>/dev/null | awk '{print $2}' | grep -qx "$name"; then
        return 0
    fi
    set_default_now "$name"
}

apply_interactive() {
    if ! pipewire_ready; then
        log_warning "PipeWire is not running yet — skip audio setup"
        log_status "After login: bash ~/.hyprgruv/lib/scripts/audio-setup.sh"
        return 0
    fi

    display_header "Sound output"

    local current
    current="$(pactl get-default-sink 2>/dev/null || true)"
    log_status "Current default: ${current:-unknown}"

    local -a names=() labels=() wpids=()
    local row name label wpid
    while IFS=$'\t' read -r name label wpid; do
        [[ -n "$name" ]] || continue
        names+=("$name")
        labels+=("$label")
        wpids+=("$wpid")
    done < <(list_sink_rows)

    if ((${#names[@]} == 0)); then
        log_warning "No audio outputs detected"
        return 0
    fi

    log_status "Detected ${#names[@]} output(s). Pick one to test — you should hear a short tone."
    echo ""

    local pick="" idx keep="" i
    while true; do
        if declare -F hyprgruv_pick >/dev/null 2>&1; then
            pick="$(hyprgruv_pick "Sound output  (test, then keep or try another)" "${labels[@]}" "Skip — keep current default")" || return 0
        elif command -v gum >/dev/null 2>&1 && declare -F gum_choose_prompt >/dev/null 2>&1; then
            pick="$(gum_choose_prompt --header "Sound output" "${labels[@]}" "Skip — keep current default")" || return 0
        else
            for i in "${!labels[@]}"; do
                printf '  %s) %s\n' "$((i + 1))" "${labels[$i]}"
            done
            printf '  %s) Skip — keep current default\n' "$((${#labels[@]} + 1))"
            read -rp "Choice: " idx
            if [[ "$idx" == "$((${#labels[@]} + 1))" ]]; then
                pick="Skip — keep current default"
            else
                pick="${labels[$((idx - 1))]:-}"
            fi
        fi

        [[ -n "$pick" ]] || return 0
        if [[ "$pick" == "Skip — keep current default" ]]; then
            log_status "Left default as-is: ${current:-unknown}"
            return 0
        fi

        idx=""
        for i in "${!labels[@]}"; do
            if [[ "${labels[$i]}" == "$pick" ]]; then
                idx="$i"
                break
            fi
        done
        [[ -n "$idx" ]] || continue

        log_status "Playing test on: ${labels[$idx]}"
        if ! play_test "${names[$idx]}"; then
            log_warning "Could not play a test tone on that device"
        fi

        keep=""
        if declare -F gum_confirm_prompt >/dev/null 2>&1; then
            if gum_confirm_prompt "Hear the test on that output? Keep it as the default?"; then
                keep=yes
            fi
        else
            read -rp "Hear it? Keep this output? [y/N]: " keep
            [[ "${keep,,}" == "y" || "${keep,,}" == "yes" ]] && keep=yes
        fi

        if [[ "$keep" == "yes" ]]; then
            set_default_now "${names[$idx]}" "${wpids[$idx]}"
            persist_choice "${names[$idx]}"
            log_success "Default output: ${labels[$idx]}"
            log_status "Saved to $SINK_FILE (re-applied on login)"
            return 0
        fi
        log_status "Try another device…"
    done
}

case "${1:-}" in
--apply | apply)
    apply_saved
    ;;
-h | --help)
    sed -n '2,8p' "$0" | sed 's/^# \?//'
    ;;
*)
    apply_interactive
    ;;
esac
