[colors.primary]
background = '#1e1d1c'
foreground = '#c6c6c6'

[colors.cursor]
text = '#c6c6c6'
cursor = '#c6c6c6'

[colors.normal]
black = '#1e1d1c'
red = '#928B78'
green = '#A0967F'
yellow = '#9F9B86'
blue = '#B3AC91'
magenta = '#C4BB9D'
cyan = '#BAC0A6'
white = '#c6c6c6'

[colors.bright]
black = '#767660'
red = '#928B78'
green = '#A0967F'
yellow = '#9F9B86'
blue = '#B3AC91'
magenta = '#C4BB9D'
cyan = '#BAC0A6'
white = '#c6c6c6'
